
name: Video Classification
description: Perform video action classification using pre-trained models. 
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-04-13"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard
    version: 2021.12

tasks:
  - type: run_session
    name: Install Dependencies
    script: cml/install_dependencies.py
    memory: 8
    cpu: 1

  - type: run_session
    name: Download Data
    script: cml/download_data.py
    memory: 4
    cpu: 1